<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        //
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 2; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 3; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 7; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 8; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 9; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 22; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 32; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 37; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 41; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 46; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 51; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 52; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 60; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 82; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 104; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 106; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 107; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 108; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 111; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 120; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 121; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 132; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 134; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 138; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 156; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 157; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 159; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 160; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 161; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 166; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 169; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 170; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 172; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 175; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 178; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 180; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 181; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 182; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 184; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 195; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 198; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 204; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 207; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 208; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 209; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 210; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 211; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 212; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 213; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 214; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 215; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 225; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 226; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 229; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 232; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 233; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 235; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 236; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 239; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 241; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 242; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 245; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 246; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 247; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 248; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 251; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 253; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 254; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 256; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 257; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 259; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 264; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 267; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 268; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 269; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 270; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 274; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 276; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 278; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 279; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 282; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 284; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 285; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 292; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 294; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 299; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 301; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 303; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 304; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 305; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 311; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 312; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 313; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 315; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 316; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 317; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 318; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 319; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 320; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 321; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 322; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 323; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 325; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 326; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 327; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 328; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 331; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 332; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 333; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 334; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 335; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 336; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 337; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 338; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 339; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 340; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 341; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 342; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 343; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 344; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 345; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 346; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 347; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 348; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 349; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 351; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 352; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 353; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 354; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 355; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 356; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 357; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 358; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 359; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 360; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 361; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 363; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 364; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 365; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 366; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 367; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 368; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 369; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 370; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 371; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 372; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 373; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 374; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 375; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 376; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 378; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 379; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 380; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 381; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 382; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 383; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 385; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 387; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 388; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 389; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 390; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 391; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 392; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 393; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 394; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 395; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 396; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 397; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 398; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 399; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 400; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 401; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 402; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 403; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 404; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 405; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 406; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 407; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 408; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 409; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 410; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 412; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 413; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 414; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 415; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 416; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 417; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 418; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 419; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 420; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 421; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 422; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 423; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 424; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 425; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 426; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 427; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 428; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 429; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 430; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 431; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 432; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 439; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 444; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 445; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 446; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 448; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 454; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 455; ");
         DB::statement("UPDATE `attributes` SET `is_required` = 1 WHERE `attributes`.`id` = 458; ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
